packages/rl_core/
├─ __init__.py
├─ algos/
│  ├─ a2c.py
│  ├─ utils.py
├─ nets/
│  ├─ shared_backbone.py
│  └─ heads.py
├─ envs/
│  ├─ make_env.py
│  └─ wrappers.py
├─ client_runtime/
│  ├─ rl_client.py              # your canonical interface
│  └─ flower_adapter.py         # bridge to Flower (fit/evaluate)
├─ evaluate/
│  └─ harness.py
├─ config/
│  ├─ a2c.yaml
│  └─ federation.yaml
└─ scripts/
   ├─ train_local.py            # sanity run (no Flower)
   └─ eval_local.py
